apiVersion: apps/v1
kind: Deployment
metadata:
  name: anonymouse
  namespace: anonymouse
spec:
  replicas: 1
  selector: { matchLabels: { app: anonymouse } }
  template:
    metadata: { labels: { app: anonymouse } }
    spec:
      containers:
      - name: anonymouse
        image: IMAGE_PLACEHOLDER
        ports: [ { containerPort: 8000 } ]
        env:
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: anonymouse
              key: DB_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: anonymouse
              key: JWT_SECRET
        - name: JWT_ALGO
          valueFrom:
            secretKeyRef:
              name: anonymouse
              key: JWT_ALGO